issuer: http://127.0.0.1:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]
  allowedHeaders: ["Authorization", "X-Requested-With"]
oauth2:
  passwordConnector: local
  responseTypes: ["code", "id_token", "token"]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      # The following configurations seem to work with OpenLDAP:
      #
      # 1) Plain LDAP, without TLS:
      host: ldap:389
      insecureNoSSL: true
      # This would normally be a read-only user.
      bindDN: cn=admin,dc=example,dc=com
      bindPW: admin
      usernamePrompt: Email Address
      userSearch:
        baseDN: ou=People,dc=example,dc=com
        filter: "(objectClass=person)"
        username: mail
        # "DN" (case sensitive) is a special attribute name. It indicates that
        # this value should be taken from the entity's DN not an attribute on
        # the entity.
        idAttr: DN
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: ou=Groups,dc=example,dc=com
        filter: "(objectClass=groupOfNames)"
        userMatchers:
          # A user is a member of a group when their DN matches
          # the value of a "member" attribute on the group entity.
          - userAttr: DN
            groupAttr: member
        # The group name should be the "cn" value.
        nameAttr: cn
  - type: github
    id: github
    name: GitHub
    config:
      clientID: {{ .Env.DEX_GITHUB_CLIENT_ID }}
      clientSecret: {{ .Env.DEX_GITHUB_CLIENT_SECRET }}
      redirectURI: http://127.0.0.1:5556/dex/callback
      loadAllGroups: true
      teamNameField: slug
      useLoginAsID: false
      orgs:
        - name: {{ .Env.DEX_GITHUB_ORG_NAME }}
          teams:
            - {{ .Env.DEX_GITHUB_ADMIN_TEAM_NAME }}
            - {{ .Env.DEX_GITHUB_USER_TEAM_NAME }}
  - type: google
    id: google
    name: Google
    config:
      clientID: {{ .Env.DEX_GOOGLE_CLIENT_ID }}
      clientSecret: {{ .Env.DEX_GOOGLE_CLIENT_SECRET }}
      redirectURI: http://127.0.0.1:5556/dex/callback
      promptType: ""
staticClients:
  - id: {{ .Env.DEX_STATIC_CLIENT_ID }}
    redirectURIs:
      - 'http://0.0.0.0:8080/docs/oauth2-redirect'
      - 'http://127.0.0.1:8080/docs/oauth2-redirect'
      - 'http://localhost:8080/docs/oauth2-redirect'
      - 'http://localhost:8080/docs/oauth2-redirect.html'
      - 'http://127.0.0.1:8080/oauth2-redirect'
    name: 'Treasury'
    secret: {{ .Env.DEX_STATIC_CLIENT_SECRET }}

enablePasswordDB: true

staticPasswords:
    - email: "user@example.com"
      hash: $2y$10$4Kqx3RD2fExgfCQXGTqat.GiclNWB6AwGtUzDPDu6Z73kaY3G7.kq
      username: "user"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    - email: "user2@example.com"
      hash: $2y$10$4Kqx3RD2fExgfCQXGTqat.GiclNWB6AwGtUzDPDu6Z73kaY3G7.kq
      username: "user2"
      userID: "96e88e65-c095-4047-9c19-c21caf253c1e"
