issuer: http://127.0.0.1:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]
  allowedHeaders: ["Authorization", "X-Requested-With"]
oauth2:
  responseTypes: ["code", "id_token", "token"]
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      # The following configurations seem to work with OpenLDAP:
      #
      # 1) Plain LDAP, without TLS:
      host: ldap:389
      insecureNoSSL: true
      # This would normally be a read-only user.
      bindDN: cn=admin,dc=example,dc=com
      bindPW: admin
      usernamePrompt: Email Address
      userSearch:
        baseDN: ou=People,dc=example,dc=com
        filter: "(objectClass=person)"
        username: mail
        # "DN" (case sensitive) is a special attribute name. It indicates that
        # this value should be taken from the entity's DN not an attribute on
        # the entity.
        idAttr: DN
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: ou=Groups,dc=example,dc=com
        filter: "(objectClass=groupOfNames)"
        userMatchers:
          # A user is a member of a group when their DN matches
          # the value of a "member" attribute on the group entity.
          - userAttr: DN
            groupAttr: member
        # The group name should be the "cn" value.
        nameAttr: cn
staticClients:
  - id: treasury
    redirectURIs:
      - 'http://0.0.0.0:8080/docs/oauth2-redirect'
      - 'http://127.0.0.1:8080/docs/oauth2-redirect'
      - 'http://localhost:8080/docs/oauth2-redirect'
      - 'http://localhost:8080/docs/oauth2-redirect.html'
    name: 'Treasury'
    secret: treasury_secret
