[package]
name = "treasury"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "^0.8.1", features = ["http2", "macros"]}
sqlx = {version = "^0.8.3", features = ["runtime-tokio", "tls-native-tls", "postgres", "derive", "migrate", "uuid", "chrono"]}
tower = "^0.5.2"
tower-http = {version = "^0.6.2", features = ["trace", "auth", "cors", "compression-gzip", "timeout"]}
tokio = {version = "^1.43.0", features = ["full"]}
thiserror = "^2.0.11"
uuid = {version = "^1.14.0", features = ["v4", "serde"]}
chrono = "^0.4.39"
serde = {version = "^1.0.218", features = ["derive"]}
serde_json = "^1.0.139"
log = "^0.4.26"
env_logger = "^0.11.6"
derive_more = {version = "^2.0.1", features = ["full"]}
casbin = "^2.10.1"
aide = { version = "^0.14.1", features = [
    "redoc",
    "swagger",
    "scalar",
    "axum-json",
    "macros",
] }
schemars = {version = "^0.8.21", features = ["chrono", "uuid1"]}
async-trait = "^0.1.86"
http-body-util = "^0.1.2"
futures-util = "^0.3.31"
reqwest = {version = "^0.12.12", features = ["json"]}
jsonwebtoken = "^9.3.1"
indexmap = "^2.7.1"
http = "^1.2.0"
