services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_DB: ${POSTGRESDB}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  dex:
    container_name: dex
    image: dexidp/dex:latest-alpine
    environment:
      DEX_GITHUB_CLIENT_ID: ${DEX_GITHUB_CLIENT_ID}
      DEX_GITHUB_CLIENT_SECRET: ${DEX_GITHUB_CLIENT_SECRET}
      DEX_GITHUB_ORG_NAME: ${DEX_GITHUB_ORG_NAME}
      DEX_GITHUB_ADMIN_TEAM_NAME: ${DEX_GITHUB_ADMIN_TEAM_NAME}
      DEX_GITHUB_USER_TEAM_NAME: ${DEX_GITHUB_USER_TEAM_NAME}
      DEX_GOOGLE_CLIENT_ID: ${DEX_GOOGLE_CLIENT_ID}
      DEX_GOOGLE_CLIENT_SECRET: ${DEX_GOOGLE_CLIENT_SECRET}
      DEX_STATIC_CLIENT_ID: ${DEX_STATIC_CLIENT_ID}
      DEX_STATIC_CLIENT_SECRET: ${DEX_STATIC_CLIENT_SECRET}
    ports:
      - 5556:5556
    volumes:
      - ./local/dex_config.yml:/etc/dex/config.docker.yaml
  ldap:
    container_name: ldap
    image: osixia/openldap:1.4.0
    command: [ "--copy-service", "--loglevel", "debug" ]
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_ORGANISATION: example
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_DOMAIN: example.com
    volumes:
      - ./local/custom_ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/custom-ldap.ldif

volumes:
  pgdata:
